name: Android - Build and Deploy

on:
  push:
    branches: [ feature/add-github-actions-for-continuous-delivery ] # release/*に書き換える
  pull_request:
    branches: [ feature/add-github-actions-for-continuous-delivery ] # release/*に書き換える

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make key.properties file
        run: |
          touch ./key.properties
          echo ${{ secrets.ENCODED_KEY_STORE }} | base64 -d > ./keystore.jks
          echo 'KEY_ALIAS=${{ secrets.KEY_ALIAS }}' >> ./key.properties
          echo 'KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}' >> ./key.properties
          echo 'STORE_FILE_PATH=/home/runner/work/upload-aab-to-google-play-console//upload-aab-to-google-play-console/keystore.jks' >> ./key.properties
          echo 'STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}' >> ./key.properties
      - name: Restore gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate AAB with increment Version Code
        run: |
          ./gradlew bundleRelease
      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.macneko.uploadsampleapp
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          # 以下のディレクトリにリリースノートを入れたら反映されそう
          # whatsNewDirectory: whatsNew


